name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Import GPG key
        id: import_gpg
        uses: mbarbero/ghaction-import-gpg@subkeys
        with:
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
        env:
          GPG_PRIVATE_KEY: ${{ secrets.CI_GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.CI_GPG_PASSPHARSE }}
          FINGERPRINT: ${{ secrets.CI_GPG_FINGERPRINT }}

      - name: GPG user IDs
        run: |
          echo "fingerprint: ${{ steps.import_gpg.outputs.fingerprint }}"
          echo "keyid:       ${{ steps.import_gpg.outputs.keyid }}"
          echo "name:        ${{ steps.import_gpg.outputs.name }}"
          echo "email:       ${{ steps.import_gpg.outputs.email }}"
          git config --global --list

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build
        run: ./gradlew clean build

      - name: Test
        run: ./gradlew test jacocoTestReport

      - name: Sign
        run: ./gradlew sign -Psigning.gnupg.homeDir=/home/runner/.gnupg -Psigning.gnupg.keyName=${{ steps.import_gpg.outputs.keyid }} -Psigning.gnupg.passphrase=${{ secrets.CI_GPG_PASSPHARSE }}