name: build

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ master ]

jobs:
  context:
    runs-on: ubuntu-latest
    outputs:
      isPR: ${{ steps.checkBranch.outputs.isPR }}
      isRelease: ${{ steps.checkBranch.outputs.isRelease }}
      version: ${{ steps.checkBranch.outputs.version }}
      semanticVersion: ${{ steps.checkBranch.outputs.semanticVersion }}

    steps:
      - uses: actions/checkout@v2

      - name: Check branch
        id: checkBranch
        shell: bash
        run: |
          cfgVer=$(grep version gradle.properties | cut -d'=' -f2)
          cfgSemantic=$(grep semanticVersion gradle.properties | cut -d'=' -f2)
          version=$([[ "${{ github.head_ref }}" =~ "release/" ]] && echo $(echo "${{ github.head_ref }}" | sed -e "s#release/##") || echo $cfgVer)
          semanticVersion=$([[ "${{ github.head_ref }}" =~ "release/" ]] && echo "" || echo $cfgSemantic)
          echo "Should Validate Version with semantic..."
          echo ::set-output name=isPR::${{ github.event_name == 'pull_request' }}
          echo ::set-output name=isRelease::${{ github.event_name == 'pull_request' && startsWith(github.head_ref, 'release/') }}
          echo ::set-output name=version::$version
          echo ::set-output name=semanticVersion::$semanticVersion
          [[ "$cfgVer$cfgSemantic" == "$version$semanticVersion" ]] && same=true || same=false
          echo "Same version: $same"
          echo ::set-output name=isSameVersion::$same

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v2
        if: ${{ steps.checkBranch.outputs.isSameVersion == 'false' }}
        with:
          git_commit_gpgsign: true
        env:
          GPG_PRIVATE_KEY: ${{ secrets.CI_GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.CI_GPG_PASSPHARSE }}

      - name: Replace version
        if: ${{ steps.checkBranch.outputs.isSameVersion == 'false' }}
        run: |
          sed -i -e "s/version=.*/version=${{ steps.checkBranch.outputs.version }}/g" gradle.properties
          sed -i -e "s/semanticVersion=.*/semanticVersion=${{ steps.checkBranch.outputs.semanticVersion }}/g" gradle.properties

      - name: GIT commit and push
        if: ${{ steps.checkBranch.outputs.isSameVersion == 'false' }}
        run: |
          git commit -S -am "<ci-auto-commit> Update version"
          git show --shortstat --show-signature
          git push


  build:
    runs-on: ubuntu-latest
    needs: context
    if: needs.context.outputs.isPR != 'true' || github.event.action != 'closed'
    steps:
      - uses: actions/checkout@v2

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v2
        with:
          git_user_signingkey: true
        env:
          GPG_PRIVATE_KEY: ${{ secrets.CI_GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.CI_GPG_PASSPHARSE }}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build
        run: |
          ./gradlew clean build -x test \
                          -Pversion=${{ needs.context.outputs.version }} \
                          -PsemanticVersion=${{needs.context.outputs.semanticVersion }} \
                          -PbuildBy="GitHub Action" -PbuildHash=${{ github.sha }}

      - name: Test
        run: ./gradlew test jacocoTestReport

      - name: SonarQube
        if: needs.context.outputs.isPR != 'true'
        run: ./gradlew sonarqube -Dsonar.login=${{ secrets.OSS_SONARQUBE_TOKEN }}

      - name: Cache SonarCloud packages
        if: needs.context.outputs.isPR != 'true'
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Publish GitHub Package
        if: needs.context.outputs.isPR != 'true'
        run: |
          ./gradlew publish -Psigning.gnupg.homeDir=/home/runner/.gnupg \
                            -Psigning.gnupg.keyName=${{ steps.import_gpg.outputs.keyid }} \
                            -Psigning.gnupg.passphrase=${{ secrets.CI_GPG_PASSPHARSE }} \
                            -Pgithub \
                            -Pnexus.username=${{ github.repository_owner }} \
                            -Pnexus.password=${{ secrets.OSS_GITHUB_TOKEN }}

      - name: Publish Sonatype OSSRH
        if: needs.context.outputs.isPR != 'true'
        run: |
          ./gradlew publish -Psigning.gnupg.homeDir=/home/runner/.gnupg \
                            -Psigning.gnupg.keyName=${{ steps.import_gpg.outputs.keyid }} \
                            -Psigning.gnupg.passphrase=${{ secrets.CI_GPG_PASSPHARSE }} \
                            -Pnexus.username=${{ secrets.OSS_SONATYPE_USER }} \
                            -Pnexus.password=${{ secrets.OSS_SONATYPE_PASSWORD }}

  tag:
    runs-on: ubuntu-latest
    needs: context
    if: needs.context.outputs.isPR == 'true' && needs.context.outputs.isRelease == 'true' && github.event.action == 'closed'
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.OSS_GITHUB_TOKEN }}

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v2
        with:
          git_commit_gpgsign: true
          git_tag_gpgsign: true
        env:
          GPG_PRIVATE_KEY: ${{ secrets.CI_GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.CI_GPG_PASSPHARSE }}

      - name: GIT tag
        run: |
          version="v${{ needs.context.outputs.version }}${{ needs.context.outputs.semanticVersion }}"
          git tag -s $version ${{ github.sha }} -m "Release $version"
          git show --shortstat --show-signature $version
          git push origin $version
