name: build

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, synchronize, reopened, closed ]
    branches: [ master ]

jobs:
  context:
    runs-on: ubuntu-latest
    outputs:
      isPR: ${{ steps.check.outputs.isPR }}
      isReleasePR: ${{ steps.check.outputs.isReleasePR }}
      version: ${{ steps.check.outputs.version }}
      semanticVersion: ${{ steps.check.outputs.semanticVersion }}
      shouldBuild: ${{ steps.check.outputs.isSameVersion == 'true' && steps.check.outputs.isAfterReleaseMerged == 'false' }}

    steps:
      - uses: actions/checkout@v2

      - name: Check
        id: check
        shell: bash
        run: |
          commitMsg="${{ github.event.commits[0].message }}"
          isPushOnMaster=${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
          isReleaseCommit=$(echo $commitMsg | grep -P -q '^Merge pull request #\d+ from .+/release/.+$' && echo 1 || echo 0)
          [[ $isPushOnMaster == true && $isReleaseCommit == 1 ]] && isAfterReleaseMerged=true || isAfterReleaseMerged=false

          isPR=${{ github.event_name == 'pull_request' }}
          isReleasePR=${{ github.event_name == 'pull_request' && startsWith(github.head_ref, 'release/') }}
          cfgVer=$(grep version gradle.properties | cut -d'=' -f2)
          cfgSemantic=$(grep semanticVersion gradle.properties | cut -d'=' -f2)
          version=$($isReleasePR == true && echo $(echo "${{ github.head_ref }}" | sed -e "s#release/##") || echo $cfgVer)
          semanticVersion=$($isReleasePR == true && echo "" || echo $cfgSemantic)
          [[ "$cfgVer$cfgSemantic" == "$version$semanticVersion" ]] && same=true || same=false

          echo "Should Validate Version with semantic..."
          echo "Version is same? $same"
          [[ $same == false && $isReleasePR == false ]] && { echo "Version is changed without release branch"; exit 1; }
          echo ::set-output name=isPR::$isPR
          echo ::set-output name=isReleasePR::$isReleasePR
          echo ::set-output name=version::$version
          echo ::set-output name=semanticVersion::$semanticVersion
          echo ::set-output name=isSameVersion::$same
          echo ::set-output name=isAfterReleaseMerged::$isAfterReleaseMerged

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v2
        if: ${{ steps.check.outputs.isSameVersion == 'false' }}
        with:
          git_commit_gpgsign: true
        env:
          GPG_PRIVATE_KEY: ${{ secrets.CI_GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.CI_GPG_PASSPHARSE }}

      - name: Replace version
        if: ${{ steps.check.outputs.isSameVersion == 'false' }}
        run: |
          sed -i -e "s/version=.*/version=${{ steps.check.outputs.version }}/g" gradle.properties
          sed -i -e "s/semanticVersion=.*/semanticVersion=${{ steps.check.outputs.semanticVersion }}/g" gradle.properties

      - name: GIT commit and push
        if: ${{ steps.check.outputs.isSameVersion == 'false' }}
        run: |
          git commit -S -am "<ci-auto-commit> Correct version"
          git show --shortstat --show-signature
          git push


  build:
    runs-on: ubuntu-latest
    needs: context
    if: needs.context.outputs.shouldBuild == 'true' && (needs.context.outputs.isPR != 'true' || github.event.action != 'closed')
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build
        run: |
          ./gradlew clean build -x test \
                          -Pversion=${{ needs.context.outputs.version }} \
                          -PsemanticVersion=${{needs.context.outputs.semanticVersion }} \
                          -PbuildBy="GitHub Action" -PbuildHash=${{ github.sha }}

      - name: Test
        run: ./gradlew test jacocoTestReport

      - name: SonarQube
        if: needs.context.outputs.isPR != 'true'
        run: ./gradlew sonarqube -Dsonar.login=${{ secrets.OSS_SONARQUBE_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache SonarCloud packages
        if: needs.context.outputs.isPR != 'true'
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v2
        if: needs.context.outputs.isPR != 'true'
        with:
          git_user_signingkey: true
        env:
          GPG_PRIVATE_KEY: ${{ secrets.CI_GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.CI_GPG_PASSPHARSE }}

      - name: Publish GitHub Package
        if: needs.context.outputs.isPR != 'true'
        run: |
          ./gradlew publish -Psigning.gnupg.homeDir=/home/runner/.gnupg \
                            -Psigning.gnupg.keyName=${{ steps.import_gpg.outputs.keyid }} \
                            -Psigning.gnupg.passphrase=${{ secrets.CI_GPG_PASSPHARSE }} \
                            -Pgithub \
                            -Pnexus.username=${{ github.repository_owner }} \
                            -Pnexus.password=${{ secrets.OSS_GITHUB_TOKEN }}

      - name: Publish Sonatype OSSRH
        if: needs.context.outputs.isPR != 'true'
        run: |
          ./gradlew publish -Psigning.gnupg.homeDir=/home/runner/.gnupg \
                            -Psigning.gnupg.keyName=${{ steps.import_gpg.outputs.keyid }} \
                            -Psigning.gnupg.passphrase=${{ secrets.CI_GPG_PASSPHARSE }} \
                            -Pnexus.username=${{ secrets.OSS_SONATYPE_USER }} \
                            -Pnexus.password=${{ secrets.OSS_SONATYPE_PASSWORD }}

  tag:
    runs-on: ubuntu-latest
    needs: context
    if: needs.context.outputs.isReleasePR == 'true' && github.event.action == 'closed' && github.event.pull_request.merged
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.OSS_GITHUB_TOKEN }}

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v2
        with:
          git_commit_gpgsign: true
          git_tag_gpgsign: true
        env:
          GPG_PRIVATE_KEY: ${{ secrets.CI_GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.CI_GPG_PASSPHARSE }}

      - name: GIT tag
        run: |
          version="v${{ needs.context.outputs.version }}${{ needs.context.outputs.semanticVersion }}"
          git tag -s $version ${{ github.sha }} -m "Release $version"
          git show --shortstat --show-signature $version
          git push origin $version
